version: '3.7'

services:

  mongo1:
    image: mongo:7.0
    command: mongod --replSet replicaTest --port 27017  --bind_ip_all --keyFile /run/secrets/MONGO_DB_KEYFILE
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGODB_PASSWORD
    networks:
    - mongo
    secrets:
    - MONGODB_USERNAME
    - MONGODB_PASSWORD
    - source: MONGO_DB_KEYFILE
      uid: '999'
      gid: '999'
      mode: 0600
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.mongo1==true]

  mongo2:
    image: mongo:7.0
    command: mongod --replSet replicaTest --port 27017 --bind_ip_all --keyFile /run/secrets/MONGO_DB_KEYFILE
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGODB_PASSWORD
    ports:
    - 27018:27017
    networks:
    - mongo
    secrets:
    - MONGODB_USERNAME
    - MONGODB_PASSWORD
    - source: MONGO_DB_KEYFILE
      uid: '999'
      gid: '999'
      mode: 0600
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.mongo2==true]

  mongo3:
    image: mongo:7.0
    command: mongod --replSet replicaTest --port 27017 --bind_ip_all --keyFile /run/secrets/MONGO_DB_KEYFILE
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGODB_PASSWORD
    ports:
    - 27019:27017
    networks:
    - mongo
    secrets:
    - MONGODB_USERNAME
    - MONGODB_PASSWORD
    - source: MONGO_DB_KEYFILE
      uid: '999'
      gid: '999'
      mode: 0600
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.mongo3==true]

  mongo-express:
    image: mongo-express
    depends_on:
    - mongo1
    - mongo2
    - mongo3
    ports:
    - 5002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/MONGODB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://usermongo:password_super_complex@mongo1,mongo2,mongo3:27017/admin?ssl=false
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
    - mongo
    secrets:
    - MONGODB_USERNAME
    - MONGODB_PASSWORD
    deploy:
      placement:
        constraints: [node.labels.mongo1==true]
      resources:
        limits:
          cpus: '0.5'
          memory: 350M
        reservations:
          cpus: '0.1'
          memory: 100M

networks:
  mongo:
  visualizer:

secrets:
  MONGODB_USERNAME:
    external: true
  MONGODB_PASSWORD:
    external: true
  MONGO_DB_KEYFILE:
    external: true
